#!/usr/bin/env python3
"""
Beta Ops Review — operational visibility for the concierge / proactivo system.

Shows current betas, their state, progress, and any pending proactive actions
generated by the SignalDetector + ActionHandler.

Usage:
    python scripts/beta_ops_review.py
    python scripts/beta_ops_review.py --json
"""

import argparse
import json
import os
import sys
from pathlib import Path
from datetime import datetime

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from state_persistence import list_all_betas
from action_handler import load_pending_actions


def _progress(slots: dict) -> str:
    if not slots:
        return "0%"
    done = sum(1 for v in slots.values() if v)
    pct = int((done / len(slots)) * 100)
    return f"{pct}%"


def main():
    parser = argparse.ArgumentParser(description="Hombre Vigente — Beta Ops Review")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    parser.add_argument("--limit", type=int, default=50, help="Max betas to show")
    args = parser.parse_args()

    betas = list_all_betas()[: args.limit]
    pending_map = {a["beta_id"]: a for a in load_pending_actions(limit=500)}

    if args.json:
        out = []
        for b in betas:
            bid = b.get("beta_id")
            out.append({
                "beta_id": bid,
                "phase": b.get("phase"),
                "next_action": b.get("next_action"),
                "progress": _progress(b.get("slots", {})),
                "last_active_at": b.get("last_active_at"),
                "turn_count": b.get("turn_count", 0),
                "pending_action": pending_map.get(bid),
            })
        print(json.dumps({"count": len(out), "betas": out}, ensure_ascii=False, indent=2))
        return

    print(f"\n=== Hombre Vigente Beta Ops Review ({len(betas)} betas) ===\n")

    for b in betas:
        bid = b.get("beta_id", "?")
        phase = b.get("phase", "?")
        next_a = b.get("next_action", "")
        prog = _progress(b.get("slots", {}))
        last = b.get("last_active_at", "never")
        turns = b.get("turn_count", 0)

        pa = pending_map.get(bid)
        pa_line = ""
        if pa:
            status = pa.get("status", "pending")
            pa_line = f"\n    → {status.upper()}: {pa['action_type']} | {pa.get('suggested_message','')[:75]}..."

        print(f"{bid:30} | {phase:20} | {prog:5} | turns={turns:3} | last={last}")
        if next_a:
            print(f"    next: {next_a}")
        if pa_line:
            print(pa_line)
        print()

    if not betas:
        print("No betas found. (Check HV_BETA_STATES_DIR or HV_STATE_PERSISTENCE)")

    if os.getenv("HV_STATE_PERSISTENCE") != "postgres":
        print("\n[Guía Agéntica] Recomendación: en producción usa Postgres como SSOT "
              "(HV_STATE_PERSISTENCE=postgres + HV_DATABASE_URL).")

    # Show overall proactive health score + is_healthy (Guía ops signal)
    try:
        from action_handler import compute_proactive_health_score
        hs = compute_proactive_health_score()
        score = hs.get("score")
        is_h = hs.get("is_healthy")
        interp = hs.get("interpretation", "")
        print(f"\nProactive Health Score: {score}/100  is_healthy={is_h}")
        print(f"  {interp}")
        if not is_h:
            print("  [ACTION] Real executes are BLOCKED unless --force. Fix SSOT/health or use force for emergencies.")
    except Exception:
        pass

    print("\n(Use /admin/betas with PIN for the API version)")
    print("Simulate proactive for a beta: curl .../admin/simulate?beta_id=xxx&pin=...  or python -c 'from action_handler import simulate_proactive_for_beta; print(simulate_proactive_for_beta(\"row-0\"))'")
    print("Execute with gate: python scripts/execute_pending_actions.py --dry-run   (add --force to bypass)")
    print("Full agent status (incl. health_score + is_healthy + metrics): /admin/agent_status (PIN)  |  /admin/metrics (PIN)")


if __name__ == "__main__":
    main()
