#!/usr/bin/env python3
"""
Script to execute (or dry-run) pending proactive actions generated by the signal + action system.

Real (non-dry) execution is gated by is_healthy (score >=70 AND postgres SSOT).
Use --force only for ops emergencies.

Usage examples:
  python scripts/execute_pending_actions.py --dry-run
  python scripts/execute_pending_actions.py --beta-id tally-xxx
  python scripts/execute_pending_actions.py --force   # bypass gate (careful!)
"""

import argparse
import json
import os
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from action_handler import execute_all_pending, load_pending_actions


def main():
    parser = argparse.ArgumentParser(description="Execute pending proactive actions for Hombre Vigente betas")
    parser.add_argument("--dry-run", action="store_true", help="Simulate sending without marking as executed")
    parser.add_argument("--beta-id", help="Only execute actions for this specific beta")
    parser.add_argument("--force", action="store_true", help="Bypass is_healthy gate (only for ops emergencies)")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    args = parser.parse_args()

    results = execute_all_pending(dry_run=args.dry_run, beta_id=args.beta_id, force=args.force)

    if args.json:
        print(json.dumps({"executed_count": len(results), "actions": results}, ensure_ascii=False, indent=2))
    else:
        mode = "DRY-RUN" if args.dry_run else "EXECUTE"
        print(f"\n[{mode}] {len(results)} actions processed\n")
        for a in results:
            print(f"- {a.get('beta_id')} | {a.get('action_type')} | status={a.get('status')}")
            msg = a.get("suggested_message", "")
            if msg:
                print(f"    message: {msg[:100]}...")

    # Show remaining pending after run
    remaining = load_pending_actions()
    print(f"\nRemaining pending actions: {len(remaining)}")

    # Log health score on exec (Aprende loop + self-correction signal)
    try:
        from action_handler import log_proactive_health_score
        hs = log_proactive_health_score()
        print(f"\nProactive Health Score after exec: {hs.get('score')}/100  is_healthy={hs.get('is_healthy')}")
    except Exception:
        pass

    # Guía SSOT reminder
    if os.getenv("HV_STATE_PERSISTENCE") != "postgres":
        print("[Guía] Para producción: usa HV_STATE_PERSISTENCE=postgres.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
